import { PendencyTable } from "../components/PendencyTable";
import { SearchBar } from "../components/SearchBar";
import { ViewContainer } from "../components/ViewContainer";
import { type ServiceRequest } from "../types/ServiceResquest";

export function PendencyView() {
  const solicitations: Array<ServiceRequest> = [
    {
      plate: "TMJ4E46",
      protocol: "a-4fg4",
      service: "Guincho",
      status: "Em base",
      datetime: "10/01 08:00",
    },
    {
      plate: "TMJ4E46",
      protocol: "a-4fg4",
      service: "Guincho",
      status: "Em base",
      datetime: "10/01 08:00",
    },
    {
      plate: "TMJ4E46",
      protocol: "a-4fg4",
      service: "Guincho",
      status: "Em base",
      datetime: "10/01 08:00",
    },
    {
      plate: "TMJ4E46",
      protocol: "a-4fg4",
      service: "Guincho",
      status: "Em base",
      datetime: "10/01 08:00",
    },
    {
      plate: "TMJ4E46",
      protocol: "a-4fg4",
      service: "Guincho",
      status: "Em base",
      datetime: "10/01 08:00",
    },
    {
      plate: "TMJ4E46",
      protocol: "a-4fg4",
      service: "Guincho",
      status: "Em base",
      datetime: "10/01 08:00",
    },
    {
      plate: "TMJ4E46",
      protocol: "a-4fg4",
      service: "Guincho",
      status: "Em base",
      datetime: "10/01 08:00",
    },
    {
      plate: "TMJ4E46",
      protocol: "a-4fg4",
      service: "Guincho",
      status: "Em base",
      datetime: "10/01 08:00",
    },
    {
      plate: "TMJ4E46",
      protocol: "a-4fg4",
      service: "Guincho",
      status: "Em base",
      datetime: "10/01 08:00",
    },
    {
      plate: "TMJ4E46",
      protocol: "a-4fg4",
      service: "Guincho",
      status: "Em base",
      datetime: "10/01 08:00",
    },
    {
      plate: "TMJ4E46",
      protocol: "a-4fg4",
      service: "Guincho",
      status: "Em base",
      datetime: "10/01 08:00",
    },
    {
      plate: "TMJ4E46",
      protocol: "a-4fg4",
      service: "Guincho",
      status: "Em base",
      datetime: "10/01 08:00",
    },
    {
      plate: "TMJ4E46",
      protocol: "a-4fg4",
      service: "Guincho",
      status: "Em base",
      datetime: "10/01 08:00",
    },
    {
      plate: "TMJ4E46",
      protocol: "a-4fg4",
      service: "Guincho",
      status: "Em base",
      datetime: "10/01 08:00",
    },
    {
      plate: "TMJ4E46",
      protocol: "a-4fg4",
      service: "Guincho",
      status: "Em base",
      datetime: "10/01 08:00",
    },
    {
      plate: "TMJ4E46",
      protocol: "a-4fg4",
      service: "Guincho",
      status: "Em base",
      datetime: "10/01 08:00",
    },
    {
      plate: "TMJ4E46",
      protocol: "a-4fg4",
      service: "Guincho",
      status: "Em base",
      datetime: "10/01 08:00",
    },
    {
      plate: "TMJ4E46",
      protocol: "a-4fg4",
      service: "Guincho",
      status: "Em base",
      datetime: "10/01 08:00",
    },
    {
      plate: "TMJ4E46",
      protocol: "a-4fg4",
      service: "Guincho",
      status: "Em base",
      datetime: "10/01 08:00",
    },
    {
      plate: "TMJ4E46",
      protocol: "a-4fg4",
      service: "Guincho",
      status: "Em base",
      datetime: "10/01 08:00",
    },
    {
      plate: "TMJ4E46",
      protocol: "a-4fg4",
      service: "Guincho",
      status: "Em base",
      datetime: "10/01 08:00",
    },
    {
      plate: "TMJ4E46",
      protocol: "a-4fg4",
      service: "Guincho",
      status: "Em base",
      datetime: "10/01 08:00",
    },
    {
      plate: "TMJ4E46",
      protocol: "a-4fg4",
      service: "Guincho",
      status: "Em base",
      datetime: "10/01 08:00",
    },
    {
      plate: "TMJ4E46",
      protocol: "a-4fg4",
      service: "Guincho",
      status: "Em base",
      datetime: "10/01 08:00",
    },
    {
      plate: "TMJ4E46",
      protocol: "a-4fg4",
      service: "Guincho",
      status: "Em base",
      datetime: "10/01 08:00",
    },
    {
      plate: "TMJ4E46",
      protocol: "a-4fg4",
      service: "Guincho",
      status: "Em base",
      datetime: "10/01 08:00",
    },
    {
      plate: "TMJ4E46",
      protocol: "a-4fg4",
      service: "Guincho",
      status: "Em base",
      datetime: "10/01 08:00",
    },
    {
      plate: "TMJ4E46",
      protocol: "a-4fg4",
      service: "Guincho",
      status: "Em base",
      datetime: "10/01 08:00",
    },
    {
      plate: "TMJ4E46",
      protocol: "a-4fg4",
      service: "Guincho",
      status: "Em base",
      datetime: "10/01 08:00",
    },
    {
      plate: "TMJ4E46",
      protocol: "a-4fg4",
      service: "Guincho",
      status: "Em base",
      datetime: "10/01 08:00",
    },
    {
      plate: "TMJ4E46",
      protocol: "a-4fg4",
      service: "Guincho",
      status: "Em base",
      datetime: "10/01 08:00",
    },
    {
      plate: "TMJ4E46",
      protocol: "a-4fg4",
      service: "Guincho",
      status: "Em base",
      datetime: "10/01 08:00",
    },
    {
      plate: "TMJ4E46",
      protocol: "a-4fg4",
      service: "Guincho",
      status: "Em base",
      datetime: "10/01 08:00",
    },
    {
      plate: "TMJ4E46",
      protocol: "a-4fg4",
      service: "Guincho",
      status: "Em base",
      datetime: "10/01 08:00",
    },
    {
      plate: "TMJ4E46",
      protocol: "a-4fg4",
      service: "Guincho",
      status: "Em base",
      datetime: "10/01 08:00",
    },
    {
      plate: "TMJ4E46",
      protocol: "a-4fg4",
      service: "Guincho",
      status: "Em base",
      datetime: "10/01 08:00",
    },
    {
      plate: "TMJ4E46",
      protocol: "a-4fg4",
      service: "Guincho",
      status: "Em base",
      datetime: "10/01 08:00",
    },
  ];

  return (
    <ViewContainer title="Atendimentos Pendentes">
      <SearchBar />
      <PendencyTable pendencies={solicitations} />
    </ViewContainer>
  );
}
